### PR TITLE
Change enb-format for block_mod

### PR DESCRIPTION
**Pull request by Vittly**
#330

### CODE REVIEW

**Comment by Vittly** [comment]
wow > "No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself."

**Comment by Vittly** [comment]
How can I restart testing in node 8? There is some flaky build problem 😞

**Comment by tadatuta** [comment]
@Vittly I've just restarted build on node 8

**Review by qfox — APPROVED** [review]

**Comment by qfox** [comment]
Thank you, man! You making a great thing for whole people of the Earth!

**Pull request merged**
